colors = {
    "Apple": ["[bold red]", "[/bold red]"],
    "Banana": ["[bold yellow]", "[/bold yellow]"],
    "Blueberry": ["[bold blue]", "[/bold blue]"],
    "Coconut": ["[bold white]", "[/bold white]"],
    "Cucumber": ["[bold green]", "[/bold green]"],
    "Grapes": ["[bold magenta]", "[/bold magenta]"],
    "Kiwi": ["[bold green]", "[/bold green]"],
    "Lemon": ["[bold yellow]", "[/bold yellow]"],
    "Lime": ["[bold green]", "[/bold green]"],
    "Mango": ["[bold orange]", "[/bold orange]"],
    "Orange": ["[bold orange]", "[/bold orange]"],
    "Papaya": ["[bold white]", "[/bold white]"],
    "Peach": ["[bold orange]", "[/bold orange]"],
    "Pear": ["[bold yellow]", "[/bold yellow]"],
    "Pineapple": ["[bold yellow]", "[/bold yellow]"],
    "Pomegranate": ["[bold red]", "[/bold red]"],
    "Raspberry": ["[bold red]", "[/bold red]"],
    "Strawberry": ["[bold red]", "[/bold red]"],
    "Tomato": ["[bold red]", "[/bold red]"],
    "Watermelon": ["[bold green]", "[/bold green]"],
    "Zucchini": ["[bold green]", "[/bold green]"],
}

rarity_order = [
    "COMMON",
    "UNCOMMON",
    "RARE",
    "EPIC",
    "LEGENDARY",
    "MYTHIC",
    "SPECIAL",
    "N/A",
]
rarity_color = {
    "COMMON": "bold white",
    "UNCOMMON": "bold green",
    "RARE": "bold blue",
    "EPIC": "bold purple",
    "LEGENDARY": "bold yellow",
    "MYTHIC": "bold magenta",
    "SPECIAL": "bold red",
    "N/A": "bold red",
}
